version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Using Amazon Corretto 8
      - mvn --version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.war   # or *.war if your pom.xml uses <packaging>war</packaging>
cache:
  paths:
    - '/root/.m2/**/*'
